import { PotholeReport } from '../types/pothole';
import { CAMPUS_CENTER } from '../data/jurisdictionsData';
import { distanceFromCampusMiles, formatCoords } from './distanceCalculator';

export function buildGgcTextReport(list: PotholeReport[]): string {
  const now = new Date().toLocaleString();
  const campusCoords = formatCoords(CAMPUS_CENTER.lat, CAMPUS_CENTER.lng);

  const lines = [
    '=======================================================',
    'GEORGIA GWINNETT COLLEGE AREA POTHOLE & HAZARD REPORT',
    '=======================================================',
    `Generated: ${now}`,
    `Reference Center: ${CAMPUS_CENTER.name} (${campusCoords})`,
    `Coverage Perimeter: ${CAMPUS_CENTER.radiusMiles} Mile Radius & Gwinnett Dispatch Grid`,
    `Total Active Hazards Tracked: ${list.length}`,
    '',
    '-------------------------------------------------------',
    'INCIDENT LOG & DISTANCE INVENTORY',
    '-------------------------------------------------------',
  ];

  list.forEach((item, index) => {
    const miles = (item.distanceFromGgcMiles ?? distanceFromCampusMiles({ lat: item.latitude, lng: item.longitude })).toFixed(2);
    const tracking = item.trackingCode || item.workOrderNumber || item.id;
    const severityUpper = (item.severity || 'medium').toUpperCase();

    lines.push(
      `${index + 1}. [${severityUpper}] ${item.title || item.roadName || 'Roadway Defect'}`,
      `   Incident Code: ${tracking}`,
      `   Coordinates:   ${formatCoords(item.latitude, item.longitude)}`,
      `   Address:       ${item.address || 'Gwinnett County Corridor'}`,
      `   Jurisdiction:  ${item.jurisdiction}`,
      `   Distance from GGC Campus Center: ${miles} miles`,
      `   Hazard Type:   ${item.hazardType || 'POTHOLE'}`,
      `   Detection:     ${item.detectedBy}`,
      `   Dimensions:    ${item.estimatedDepthInches || 3.0}" Depth x ${item.estimatedWidthInches || 18}" Width (${item.surfaceType || 'Asphalt'})`,
      `   Status:        ${item.status.toUpperCase()}`,
      `   Notes/Context: ${item.description || 'No notes reported.'}`,
      ''
    );
  });

  lines.push(
    '-------------------------------------------------------',
    'GGC & GWINNETT COUNTY DISPATCH DIRECTORY NOTICE',
    '-------------------------------------------------------',
    'Campus Incidents: facilities@ggc.edu | (678) 407-5533 (SLA 24-48 hrs)',
    'County Roads:     dotcustomerservice@gwinnettcounty.com | (770) 822-7400',
    'State Routes:     District1Dispatch@dot.ga.gov | Dial 511 (GDOT)',
    '',
    'Notice: Generated by Georgia Pothole Patrol & Transportation Dispatch Hub.',
    'Please verify roadway coordinates prior to field crew dispatch.'
  );

  return lines.join('\n');
}

export function downloadTextReport(list: PotholeReport[], filename: string = 'ggc-pothole-report.txt') {
  const text = buildGgcTextReport(list);
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
