import React from 'react';
import { PotholeReport } from '../../types/pothole';
import { 
  CheckCircle2, 
  AlertTriangle, 
  MapPin, 
  PlusCircle, 
  Clock, 
  ThumbsUp, 
  ExternalLink,
  Shield,
  Layers
} from 'lucide-react';

interface MyReportsViewProps {
  potholes: PotholeReport[];
  onSelectPothole: (p: PotholeReport) => void;
  onOpenReportModal: () => void;
  onNavigateToMap: () => void;
}

export const MyReportsView: React.FC<MyReportsViewProps> = ({
  potholes,
  onSelectPothole,
  onOpenReportModal,
  onNavigateToMap
}) => {
  // Filter for reports generated by the user or confirmed by them
  const myReports = potholes.filter(
    p => p.source === 'user' || (p.userConfirmed && p.id.startsWith('GW-POT-'))
  );

  const getStatusColor = (status: PotholeReport['status']) => {
    switch (status) {
      case 'repaired':
        return 'bg-emerald-950 text-emerald-300 border-emerald-800';
      case 'scheduled':
        return 'bg-blue-950 text-blue-300 border-blue-800';
      case 'investigating':
        return 'bg-amber-950 text-amber-300 border-amber-800';
      default:
        return 'bg-slate-800 text-slate-300 border-slate-700';
    }
  };

  const getStatusStep = (status: PotholeReport['status']) => {
    switch (status) {
      case 'reported': return 1;
      case 'investigating': return 2;
      case 'scheduled': return 3;
      case 'repaired': return 4;
      default: return 1;
    }
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-6 space-y-6">
      
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-slate-900 border border-slate-800 rounded-3xl p-5 sm:p-6 shadow-xl">
        <div>
          <h2 className="text-xl sm:text-2xl font-extrabold text-white tracking-tight flex items-center gap-2">
            <CheckCircle2 className="w-6 h-6 text-teal-400" />
            <span>My Submitted Road Reports</span>
          </h2>
          <p className="text-xs sm:text-sm text-slate-400 mt-1">
            Track real-time municipal inspection, scheduling, and repair status for hazards you reported.
          </p>
        </div>

        <button
          onClick={onOpenReportModal}
          className="px-4 py-2.5 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white font-bold rounded-xl text-xs shadow-lg shadow-teal-500/20 transition flex items-center justify-center gap-2 active:scale-95 shrink-0"
        >
          <PlusCircle className="w-4 h-4" />
          <span>Report New Hazard</span>
        </button>
      </div>

      {/* Reports List or Empty State */}
      {myReports.length === 0 ? (
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-10 text-center space-y-4">
          <div className="w-16 h-16 rounded-2xl bg-slate-800 flex items-center justify-center mx-auto text-slate-500">
            <AlertTriangle className="w-8 h-8" />
          </div>
          <div className="space-y-1 max-w-md mx-auto">
            <h3 className="text-base font-bold text-white">No hazards reported from this device yet</h3>
            <p className="text-xs text-slate-400">
              When you submit a pothole report using the camera, map tap, or Drive Sensor, your submissions will appear here with live tracking.
            </p>
          </div>
          <div className="flex items-center justify-center gap-3 pt-2">
            <button
              onClick={onOpenReportModal}
              className="px-4 py-2 bg-teal-600 hover:bg-teal-500 text-white font-bold rounded-xl text-xs shadow transition"
            >
              Submit Pothole Report
            </button>
            <button
              onClick={onNavigateToMap}
              className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 font-semibold rounded-xl text-xs border border-slate-700 transition"
            >
              Explore Map
            </button>
          </div>
        </div>
      ) : (
        <div className="space-y-4">
          {myReports.map((report) => {
            const step = getStatusStep(report.status);

            return (
              <div
                key={report.id}
                onClick={() => onSelectPothole(report)}
                className="bg-slate-900 border border-slate-800 hover:border-slate-700 rounded-3xl p-5 shadow-xl transition cursor-pointer space-y-4 group"
              >
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                  <div>
                    <div className="flex items-center space-x-2">
                      <span className={`px-2.5 py-0.5 rounded-md text-[10px] font-bold uppercase tracking-wider border ${getStatusColor(report.status)}`}>
                        {report.status}
                      </span>
                      <span className="text-xs font-mono text-slate-400">
                        {report.trackingCode || report.id}
                      </span>
                    </div>
                    <h3 className="text-base font-bold text-white group-hover:text-teal-300 transition mt-1">
                      {report.title}
                    </h3>
                    <p className="text-xs text-slate-400 flex items-center gap-1.5 mt-0.5">
                      <MapPin className="w-3.5 h-3.5 text-slate-500 shrink-0" />
                      <span>{report.address || `${report.roadName}, ${report.city}`}</span>
                    </p>
                  </div>

                  <div className="text-left sm:text-right">
                    <span className="text-xs font-bold text-teal-400 flex items-center sm:justify-end gap-1">
                      <span>👆</span>
                      <span>{report.verificationsCount} drivers confirmed</span>
                    </span>
                    <span className="text-[11px] text-slate-500 block mt-0.5">
                      {report.jurisdiction}
                    </span>
                  </div>
                </div>

                {/* Progress Pipeline */}
                <div className="pt-2 border-t border-slate-800">
                  <div className="flex items-center justify-between text-[11px] text-slate-400 mb-1.5">
                    <span className={step >= 1 ? 'text-teal-400 font-bold' : ''}>1. Reported</span>
                    <span className={step >= 2 ? 'text-teal-400 font-bold' : ''}>2. Investigating</span>
                    <span className={step >= 3 ? 'text-teal-400 font-bold' : ''}>3. Scheduled</span>
                    <span className={step >= 4 ? 'text-emerald-400 font-bold' : ''}>4. Repaired</span>
                  </div>
                  <div className="grid grid-cols-4 gap-1.5 h-1.5 bg-slate-800 rounded-full overflow-hidden">
                    <div className={`h-full rounded-full ${step >= 1 ? 'bg-teal-500' : 'bg-transparent'}`} />
                    <div className={`h-full rounded-full ${step >= 2 ? 'bg-teal-500' : 'bg-transparent'}`} />
                    <div className={`h-full rounded-full ${step >= 3 ? 'bg-teal-500' : 'bg-transparent'}`} />
                    <div className={`h-full rounded-full ${step >= 4 ? 'bg-emerald-400' : 'bg-transparent'}`} />
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

    </div>
  );
};
